//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 核素识别仪.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("核素识别仪.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 CPS： 的本地化字符串。
        /// </summary>
        public static string Res_CPS {
            get {
                return ResourceManager.GetString("Res_CPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPS阈值设置： 的本地化字符串。
        /// </summary>
        public static string Res_CPS阈值设置 {
            get {
                return ResourceManager.GetString("Res_CPS阈值设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ROI分析结果 的本地化字符串。
        /// </summary>
        public static string Res_ROI分析结果 {
            get {
                return ResourceManager.GetString("Res_ROI分析结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口不存在或被占用！ 的本地化字符串。
        /// </summary>
        public static string Res_串口不存在或被占用 {
            get {
                return ResourceManager.GetString("Res_串口不存在或被占用", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口号 的本地化字符串。
        /// </summary>
        public static string Res_串口号 {
            get {
                return ResourceManager.GetString("Res_串口号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口已关闭 的本地化字符串。
        /// </summary>
        public static string Res_串口已关闭 {
            get {
                return ResourceManager.GetString("Res_串口已关闭", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口已打开 的本地化字符串。
        /// </summary>
        public static string Res_串口已打开 {
            get {
                return ResourceManager.GetString("Res_串口已打开", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口设置 的本地化字符串。
        /// </summary>
        public static string Res_串口设置 {
            get {
                return ResourceManager.GetString("Res_串口设置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Res_保存 {
            get {
                return ResourceManager.GetString("Res_保存", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存文件 的本地化字符串。
        /// </summary>
        public static string Res_保存文件 {
            get {
                return ResourceManager.GetString("Res_保存文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Res_停止 {
            get {
                return ResourceManager.GetString("Res_停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止位 的本地化字符串。
        /// </summary>
        public static string Res_停止位 {
            get {
                return ResourceManager.GetString("Res_停止位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止稳峰 的本地化字符串。
        /// </summary>
        public static string Res_停止稳峰 {
            get {
                return ResourceManager.GetString("Res_停止稳峰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭串口 的本地化字符串。
        /// </summary>
        public static string Res_关闭串口 {
            get {
                return ResourceManager.GetString("Res_关闭串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支比 的本地化字符串。
        /// </summary>
        public static string Res_分支比 {
            get {
                return ResourceManager.GetString("Res_分支比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Res_删除 {
            get {
                return ResourceManager.GetString("Res_删除", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剂量率： 的本地化字符串。
        /// </summary>
        public static string Res_剂量率 {
            get {
                return ResourceManager.GetString("Res_剂量率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Res_加载失败 {
            get {
                return ResourceManager.GetString("Res_加载失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载成功 的本地化字符串。
        /// </summary>
        public static string Res_加载成功 {
            get {
                return ResourceManager.GetString("Res_加载成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半衰期 的本地化字符串。
        /// </summary>
        public static string Res_半衰期 {
            get {
                return ResourceManager.GetString("Res_半衰期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Res_取消 {
            get {
                return ResourceManager.GetString("Res_取消", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string Res_失败 {
            get {
                return ResourceManager.GetString("Res_失败", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间： 的本地化字符串。
        /// </summary>
        public static string Res_开始时间 {
            get {
                return ResourceManager.GetString("Res_开始时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前核素列表 的本地化字符串。
        /// </summary>
        public static string Res_当前核素列表 {
            get {
                return ResourceManager.GetString("Res_当前核素列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在核素库 的本地化字符串。
        /// </summary>
        public static string Res_所在核素库 {
            get {
                return ResourceManager.GetString("Res_所在核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动稳峰 的本地化字符串。
        /// </summary>
        public static string Res_手动稳峰 {
            get {
                return ResourceManager.GetString("Res_手动稳峰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动识别 的本地化字符串。
        /// </summary>
        public static string Res_手动识别 {
            get {
                return ResourceManager.GetString("Res_手动识别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开串口 的本地化字符串。
        /// </summary>
        public static string Res_打开串口 {
            get {
                return ResourceManager.GetString("Res_打开串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        public static string Res_打开文件 {
            get {
                return ResourceManager.GetString("Res_打开文件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描串口 的本地化字符串。
        /// </summary>
        public static string Res_扫描串口 {
            get {
                return ResourceManager.GetString("Res_扫描串口", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Res_提示 {
            get {
                return ResourceManager.GetString("Res_提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索核素名称: 的本地化字符串。
        /// </summary>
        public static string Res_搜索核素名称 {
            get {
                return ResourceManager.GetString("Res_搜索核素名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        public static string Res_数据位 {
            get {
                return ResourceManager.GetString("Res_数据位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示未识别的峰 的本地化字符串。
        /// </summary>
        public static string Res_是否显示未识别的峰 {
            get {
                return ResourceManager.GetString("Res_是否显示未识别的峰", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小分支比: 的本地化字符串。
        /// </summary>
        public static string Res_最小分支比 {
            get {
                return ResourceManager.GetString("Res_最小分支比", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未识别 的本地化字符串。
        /// </summary>
        public static string Res_未识别 {
            get {
                return ResourceManager.GetString("Res_未识别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准能量(keV) 的本地化字符串。
        /// </summary>
        public static string Res_标准能量keV {
            get {
                return ResourceManager.GetString("Res_标准能量keV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位 的本地化字符串。
        /// </summary>
        public static string Res_校验位 {
            get {
                return ResourceManager.GetString("Res_校验位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核素名称 的本地化字符串。
        /// </summary>
        public static string Res_核素名称 {
            get {
                return ResourceManager.GetString("Res_核素名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核素库 的本地化字符串。
        /// </summary>
        public static string Res_核素库 {
            get {
                return ResourceManager.GetString("Res_核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核素活度刻度因子 的本地化字符串。
        /// </summary>
        public static string Res_核素活度刻度因子 {
            get {
                return ResourceManager.GetString("Res_核素活度刻度因子", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核素能量分支 的本地化字符串。
        /// </summary>
        public static string Res_核素能量分支 {
            get {
                return ResourceManager.GetString("Res_核素能量分支", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 核素识别 的本地化字符串。
        /// </summary>
        public static string Res_核素识别 {
            get {
                return ResourceManager.GetString("Res_核素识别", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索 的本地化字符串。
        /// </summary>
        public static string Res_检索 {
            get {
                return ResourceManager.GetString("Res_检索", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        public static string Res_波特率 {
            get {
                return ResourceManager.GetString("Res_波特率", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量活度 的本地化字符串。
        /// </summary>
        public static string Res_测量活度 {
            get {
                return ResourceManager.GetString("Res_测量活度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Res_添加 {
            get {
                return ResourceManager.GetString("Res_添加", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您希望将此核素信息添加到哪个核素库？ 的本地化字符串。
        /// </summary>
        public static string Res_添加到核素库 {
            get {
                return ResourceManager.GetString("Res_添加到核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Res_清空 {
            get {
                return ResourceManager.GetString("Res_清空", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Res_确定 {
            get {
                return ResourceManager.GetString("Res_确定", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑核素库: 的本地化字符串。
        /// </summary>
        public static string Res_编辑核素库 {
            get {
                return ResourceManager.GetString("Res_编辑核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置信度 的本地化字符串。
        /// </summary>
        public static string Res_置信度 {
            get {
                return ResourceManager.GetString("Res_置信度", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能量(keV) 的本地化字符串。
        /// </summary>
        public static string Res_能量 {
            get {
                return ResourceManager.GetString("Res_能量", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义新核素库名称： 的本地化字符串。
        /// </summary>
        public static string Res_自定义新核素库名称 {
            get {
                return ResourceManager.GetString("Res_自定义新核素库名称", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数： 的本地化字符串。
        /// </summary>
        public static string Res_计数 {
            get {
                return ResourceManager.GetString("Res_计数", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数率监测 的本地化字符串。
        /// </summary>
        public static string Res_计数率监测 {
            get {
                return ResourceManager.GetString("Res_计数率监测", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        public static string Res_计算 {
            get {
                return ResourceManager.GetString("Res_计算", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算能量(keV) 的本地化字符串。
        /// </summary>
        public static string Res_计算能量keV {
            get {
                return ResourceManager.GetString("Res_计算能量keV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别核素列表 的本地化字符串。
        /// </summary>
        public static string Res_识别核素列表 {
            get {
                return ResourceManager.GetString("Res_识别核素列表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别核素结果 的本地化字符串。
        /// </summary>
        public static string Res_识别核素结果 {
            get {
                return ResourceManager.GetString("Res_识别核素结果", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string Res_详情 {
            get {
                return ResourceManager.GetString("Res_详情", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 误差(%) 的本地化字符串。
        /// </summary>
        public static string Res_误差 {
            get {
                return ResourceManager.GetString("Res_误差", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请在谱图上框选需要分析的范围 的本地化字符串。
        /// </summary>
        public static string Res_请在谱图上框选需要分析的范围 {
            get {
                return ResourceManager.GetString("Res_请在谱图上框选需要分析的范围", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谱图采集 的本地化字符串。
        /// </summary>
        public static string Res_谱图采集 {
            get {
                return ResourceManager.GetString("Res_谱图采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择使用中的核素库： 的本地化字符串。
        /// </summary>
        public static string Res_选择使用中的核素库 {
            get {
                return ResourceManager.GetString("Res_选择使用中的核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择区域 的本地化字符串。
        /// </summary>
        public static string Res_选择区域 {
            get {
                return ResourceManager.GetString("Res_选择区域", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择核素库: 的本地化字符串。
        /// </summary>
        public static string Res_选择核素库 {
            get {
                return ResourceManager.GetString("Res_选择核素库", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要识别的核素 的本地化字符串。
        /// </summary>
        public static string Res_选择要识别的核素 {
            get {
                return ResourceManager.GetString("Res_选择要识别的核素", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 道址 的本地化字符串。
        /// </summary>
        public static string Res_道址 {
            get {
                return ResourceManager.GetString("Res_道址", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集 的本地化字符串。
        /// </summary>
        public static string Res_采集 {
            get {
                return ResourceManager.GetString("Res_采集", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集时间(s)： 的本地化字符串。
        /// </summary>
        public static string Res_采集时间 {
            get {
                return ResourceManager.GetString("Res_采集时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Res_重置 {
            get {
                return ResourceManager.GetString("Res_重置", resourceCulture);
            }
        }
    }
}
